### ISSUE TITLE
Possible scam site? netexcoins.com

### ISSUE THREAD

**Issue by marianopw** [CryptoScamDB/blacklist#180]
After reporting some scam sites on this reddit post:
https://www.reddit.com/r/Bitcoin/comments/d6l97g/be_aware_ongoing_btc_scam_on_discord/

I started searching for more of this scams sites using the default 'contact address' (110 Bishopsgate, London EC2N 4AD, UK)
Found a lot more clones but thanfully they are almost all being flagged as phishing sites.

I found this other site, which is a lot like the other scam sites, but with a different design.
Strangely enough, they use the same '110 Bishopsgate, London' address, and the texts look a lot like the ones found on the reported scam sites.
The site is:
https://netexcoins.com/

Anyone knows if this is legit?

**Comment by 409H** [comment]
Thanks for the report
