### ISSUE TITLE
More scam sites

### ISSUE THREAD

**Issue by marianopw** [CryptoScamDB/blacklist#181]
https://cryptogood.000webhostapp.com/about
https://delltrade.com/about
https://yobit.website/about/

This is the search im doing to find all these sites.

https://duckduckgo.com/?q=%22company+begins+its+history+from+July+2017%2C+when+it+was+developed+and+registered+by+our+founder%22&t=ffab&atb=v180-1&ia=web

pretty easy to find lol

**Comment by 409H** [comment]
Thanks for the report
