### ISSUE TITLE
binancechange.com BTC Scam Discord

### ISSUE THREAD

**Issue by itzleafar** [CryptoScamDB/blacklist#228]
rocketGood news! You have been randomly selected among active discord users.rocket

The Binance campaign made the largest airdrop among active discord users totaling 6833 ETH. We did this to promote our new binancechange.com platform, where you can take your winnings. Using the code, you will receive a random amount in the amount of 3 to 30 ETH

money_mouth YOU WIN 23 Ethereum money_mouth

To receive your winnings you need:
rotating_light 1. Sign up for our new https://binancechange.com platform

rotating_light 2. Go to the "code" tab and activate your code: BE2055580F740294 ( https://binancechange.com/en/codes)

rotating_light 3. Go to the "balance" tab and withdraw your winnings to a convenient wallet

   bulb    Have questions? bulb
Contact us at online support.
https://binancechange.com/en/support

With best wishes,
Binance Company!

**Comment by gabgagnon** [comment]
Same for Laubit.com. I got contacted by Discord.

**Comment by 409H** [comment]
Thanks - added to blacklist in https://github.com/MetaMask/eth-phishing-detect/pull/3860
