### ISSUE TITLE
spacexgives[.]com

### ISSUE THREAD

**Issue by kravietz** [CryptoScamDB/blacklist#245]
Once again, spamvertised on Twitter https://spacexgives.com/ e.g. 
https://twitter.com/jbcoopr/status/1254062533222240256?s=20

BTC `1JcvfyRmDNX9T2WywC5sP3CNexzuvrrpiS`
ETH `0xddebf00FbC27F7BAF0bef3fA3665473Eec46BC63`

**Comment by kravietz** [comment]
Similar campaign twitter20.com and https://telegra.ph/Twitter-Official-BTC-Giveaway-04-24

BTC `1rdbv5yXwLMmrnw8r9vVvnUFSCanAQEu6`

**Comment by 409H** [comment]
Thanks - blacklisted in https://github.com/CryptoScamDB/blacklist/commit/ee964a85780e0da90131d6dddfb74f9dcaea4c65
