### ISSUE TITLE
lauBIT bitcoin scam on discord

### ISSUE THREAD

**Issue by gabgagnon** [CryptoScamDB/blacklist#255]
Here's the message:

seedling  LauBIT Financial Company OÜ seedling
gemGiveaway News!  gem Congratulations! gem

mask During this difficult time for all people, during the coronavirus pandemic, our company distributes 30 bitcoins in collaboration with various funds and our business partners

game_die You have been randomly selected among users of  Discord Servers, such as: Binance / TronNetowrkEn / BitTorrrent / BitMax / BitMart and many others ... In the Giveaway! We are fast-growing crypto project which offers the best conditions to hold or trade your Crypto! To attract new users, we did a free giveaway with 100 prizes worth almost 30 BTC!

moneybag You won 0.6711 BTC moneybag

gemHow to use and get your BTC? gem

arrow_right Sign up on the site: https://laubit.com/
arrow_right  Go to  menu section"Codes"  and activate your code:  
arrow_right Withdraw BTC to your external  wallet.
arrow_right Done!

bangbangDo not give this Code to another person
bangbangThis Code is valid 3 day from the date of issue.

warningDo you have questions about winnings? warning
globe_with_meridians Online Support on the site.  https://laubit.com/en/support

gemBest Wishes,
LauBit Team!  mask Take care of yourself  & Stay at home

**Comment by 409H** [comment]
Thanks - added to blacklist in https://github.com/CryptoScamDB/blacklist/pull/257 https://github.com/MetaMask/eth-phishing-detect/pull/3860
