### ISSUE TITLE
Discord scam

### ISSUE THREAD

**Issue by DCandE** [CryptoScamDB/blacklist#304]
Congratulations!
:satellite_antenna:You became a winner in our random number of cryptocurrency GIVEAWAY.

In order to help people in such a difficult time, our company Hederabit and our partners decided to make a mass draw and give cryptocurrency from 0.001 to 0.9 BTC to random users
Only for users over 18 years old.(SYSTEM CAN ASK TO VERIFY YOUR AGE) 

You WON 0.5236 BTC
        Your promocode: ****************************
 
How to start using the site?
Register an account on the site. https://hederabit.com/
Go on Page "Codes".
Activate promotional code
Receive BTC on your account.
 Go to the Balance tab and click on the "Withdraw" next to the desired coin, enter the address and the amount.

If you have any questions, contact us in online support.
                 https://hederabit.com/en/support 

IF YOU DONT KNOW WHAT IS CRYPTO AND HOW TO USE IT (PLEASE IGNORE THIS MESSAGE

2020 hederabit.com All rights reserved

**Comment by 409H** [comment]
Thanks! Pushed in https://github.com/CryptoScamDB/blacklist/pull/305 - also pivoted the infrastructure and found a couple more
